---
atomic_number: 18
epsilon: 0.010323 # eV
sigma: 3.40 # Å
cutoff: 6.625 # Å
a : 5.256E-10 # Lattice constant
# Insert None for the unused lattice constants (e.g. [3.569,None,None,None,None,None] for SC/FCC/BCC lattice) 
latticeconstants : [3.6147,None,None,None,None,None] #[a, b, c, alpha, beta, gamma]
#bravaislattice currently only supports "SC", "FCC", "BCC" 
bravaislattice : #(conventional unit cell)
directions : [[1,0,0], [0,1,0], [0,0,1]] #(use Miller-Bravais for hex-structure), hex currently not supported
#Customizable primitive unit cell, leave bravaislattice empty if cell is used.
cell: [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]] #(primitive unit cell vectors)
positions : [[0,0,0]] #Set position of each atom in the molecule
symbol : "Ar" 
make_traj: True
pbc : True #periodic boundary conditions
size : [15,15,15]
temperature_K : 80
# Leave potential empty if running ASE, will resort to using EMT as potential.
potential: "openKIM"
run_density: False
run_density_plot: False
run_MD: True
run_pressure: True
iterations: 20000
interval: 400
openKIMid: "Exp6_KongChakrabarty_1973_ArNe__MO_946046425752_002"
