---
Element: 'diamond'
Z: 8 #Number of atoms
M: 12 #Molar mass
Na: 6.023E+23 #avogadros constant
a: 3.569E-8 #Lattice constant
directions : [[1,0,0], [0,1,0], [0,0,1]]
symbol : "Cu"
temperature_K : 300
run_density: True
run_MD: True
directions : [[1,0,0], [0,1,0], [0,0,1]]
symbol : "Cu"
temperature_K : 300
