---
Element: 'argon'
Z: 4 # Number of atoms
M: 1 # Molar mass
atomic_number: 18
epsilon: 0.010323 # eV
sigma: 3.40 # Å
cutoff: 6.625 # Å
Na: 6.023E+23 # avogadros constant
a : 5.256E-10 # Lattice constant
latticeconstants : [3.569, 4.569, 5.569, 50, 60, 70] #[a, b, c, alpha, beta, gamma]
structure : "FCC"
directions : [[1,0,0], [0,1,0], [0,0,1]] #use Miller-Bravais for hex-structure
symbol : "Cu"
make_traj: True
pbc : True
size : 1
temperature_K : 40
potential: #leave empty if using ASE for now
run_density: False
run_MD: True
run_pressure: True
iterations: 2000
interval: 100
