---
#-----------Atoms Setup------------#
latticeconstant : 3.6147 #Only supporting cubic lattices with one parameter
cell: [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]] #(primitive unit cell vectors)
positions : [[0,0,0]] #Set position of each atom relative to each other in the molecule (lists in list)
symbol : "Ar"
pbc : True #periodic boundary conditions
size : 15 # Repeating unit cell in each dimension (e.g. 2 -> 2^3 = 8 times as large)

#-----------Simulation Setup------------#
make_traj: True
run_MD: True
ensemble: "NVT" #Choose NVT or NVE
NVT_friction: 0.02
temperature_K : 300
# set potential to 'LJ' to use built in LennardJones
# prefix with 'openKIM:' to use corresponding openKIM potential
potential: "openKIM:LJ_Smoothed_Bernardes_1958_Ar__MO_764178710049_001"
# Equilibrium checks only supports about 700+ atoms systems reliably. For more info
# consult the documentation
checkForEquilibrium : True
dt: 5 # simulation time step [fs]
# Number of iterations after equilibrium has been reached or timeout in the equilibrium
# check  
iterations: 5000
interval: 100

#-----------Analyse------------#
run_density: True
density_time: 1 #If wanted to specify what timestep the density is to be calculated. Empty = first timestep

run_MSD: True
MSD_time: #If wanted to specify what timestep the mean square displacement is to be calculated. Empty = first timestep

run_self_diffusion_coefficient: True
self_diffusion_coefficient_time: #If wanted to specify what timestep the self diffusion coefficient is to be calculated. Empty = first timestep

run_pressure: True

output: #What material parameters to calculate and output from the traj-file?
  - temperature
  - volume

#-----------Visualize------------#
visualize:
  - temperature
run_density_plot: False
run_MSD_plot: False
