---
#-----------Atoms Setup------------#
latticeconstant : 7.05465000 #Only supporting cubic lattices with one parameter
guess_latticeconstant: 7.05465000
cell: "sc" #(primitive unit cell vectors)
scaled_positions : [ #Set position of each atom relative to each other in the molecule (lists in list)
  [0.06340700, 0.06340700, 0.06340700],
  [0.43659300, 0.93659300, 0.56340700],
  [0.56340700, 0.43659300, 0.93659300],
  [0.93659300, 0.56340700, 0.43659300],
  [0.68255600, 0.68255600, 0.68255600],
  [0.81744400, 0.31744400, 0.18255600],
  [0.18255600, 0.81744400, 0.31744400],
  [0.31744400, 0.18255600, 0.81744400],
  [0.78510900, 0.94922100, 0.38618900],
  [0.38618900, 0.78510900, 0.94922100],
  [0.94922100, 0.38618900, 0.78510900],
  [0.55077900, 0.61381100, 0.28510900],
  [0.88618900, 0.71489100, 0.05077900],
  [0.05077900, 0.88618900, 0.71489100],
  [0.11381100, 0.21489100, 0.44922100],
  [0.61381100, 0.28510900, 0.55077900],
  [0.44922100, 0.11381100, 0.21489100],
  [0.28510900, 0.55077900, 0.61381100],
  [0.21489100, 0.44922100, 0.11381100],
  [0.71489100, 0.05077900, 0.88618900],
]
symbol : "Al4Au16"
pbc : True #periodic boundary conditions
size : 10   # Repeating unit cell in each dimension (e.g. 2 -> 2^3 = 8 times as large)

#-----------Simulation Setup------------#
make_traj: True
run_MD: True
ensemble: "NVT" #Choose NVT or NVE
NVT_friction: 0.2
temperature_K : 300
checkForEquilibrium : True
# set potential to 'LJ' to use built in LennardJones
# prefix with 'openKIM:' to use corresponding openKIM potential
#potential: "openKIM:Morse_EIP_GuthikondaElliott_2011_AuCd__MO_703849496106_002"
potential: "openKIM:EMT_Asap_Standard_JacobsenStoltzeNorskov_1996_AlAgAuCuNiPdPt__MO_115316750986_001"
dt: 5 # simulation time step [fs]
iterations: 10000
interval: 100
checkForEquilibrium: True
calculateCohesiveEnergy: True
max_iterations_coh_E: 200

#-----------Analyse------------#
output:
  - Temperature
  - Volume
  - Specific Heat Capacity
  - Density
  - Instant Pressure
  - Average Pressure
  - MSD
  - Self Diffusion Coefficient
  - Self Diffusion Coefficient Array
  - Lindemann criterion
  - Optimal Lattice Constant
  - Optimal Lattice Volume
  - Bulk Modulus
  - Debye Temperature
  - Transversal Sound Wave Velocity
  - Longitudinal Sound Wave Velocity
  - Shear Modulus
  - Cohesive Energy

#-----------Visualize------------#
visualize:
  - Lattice
  - MSD
  - Temperature
  #- Scatter
scatter_type_d1: "Debye Temperature" #chooses which type of data to write to x-axis.
scatter_type_d2: "Specific Heat Capacity" #chooses which type of data to write to y-axis.
scatter_dir: out_CdAu3 #Chooses which directory to read .json files from. Leave empty and it will search for .json files in the main dir.
scatter_files: [] #Chooses which .json files that user wants to do scatterplot of. Leave empty and it will use all the files in choosen directory.
run_density_plot: False
run_MSD_plot: False
