---
#-----------Atoms Setup------------#
latticeconstant : 3.61 #Only supporting cubic lattices with one parameter
cell: [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]] #(primitive unit cell vectors)
scaled_positions : [[0,0,0]] #Set position of each atom relative to each other in the molecule (lists in list)
symbol : "Cu" 
pbc : True #periodic boundary conditions
size : 10 # Repeating unit cell in each dimension (e.g. 2 -> 2^3 = 8 times as large)

#-----------Simulation Setup------------#
make_traj: True
run_MD: True
ensemble: "NVE" #Choose NVT or NVE
NVT_friction: 0.2
temperature_K : 300
output:
  - Temperature
  - Volume
  - Debye Temperature
  - Self Diffusion Coefficient
  - Density
  - Pressure
  - MSD
  - Self Diffusion Coefficient Array
# set potential to 'LJ' to use built in LennardJones
# prefix with 'openKIM:' to use corresponding openKIM potential
potential: "openKIM:Sim_ASAP_EMT_Rasmussen_AgAuCu__SM_847706399649_000"
dt: 5 # simulation time step [fs]
iterations: 500
interval: 20

#-----------Analyse------------#
run_density: True
density_time: 1 #If wanted to specify what timestep the density is to be calculated. Empty = first timestep

run_self_diffusion_coefficient: True

run_pressure: True

#-----------Visualize------------#
visualize:
  - temperature
  - MSD
run_density_plot: True
