---
Element: 'Argon'
Z: 1 # Number of atoms
M: 39.9 # Molar mass
atomic_number: 18
epsilon: 0.010323 # eV
sigma: 3.40 # Å
cutoff: 6.25 # Å
Na: 6.023E+23 # avogadros constant
a : 5.256E-10 # Lattice constant
# Insert None for the unused lattice constants (e.g. [3.569,None,None,None,None,None] for SC/FCC/BCC lattice) 
latticeconstants : [3.569,None,None,None,None,None] #[a, b, c, alpha, beta, gamma]
#bravaislattice currently only supports "SC", "FCC", "BCC" 
bravaislattice : "FCC" #(conventional unit cell)
#Customizable primitive unit cell, leave bravaislattice empty if cell is used. 
cell: [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]] #(primitive unit cell vectors)
directions : [[1,0,0], [0,1,0], [0,0,1]] #(use Miller-Bravais for hex-structure), hex currently not supported
symbol : "Cu"
make_traj: True
pbc : True #periodic boundary conditions
size : [15,15,15]
temperature_K : 0
# Leave potential empty if running ASE, will resort to using EMT as potential.
potential: "EMT"
ensamble : "NVE"
run_density: False
run_MD: True
run_pressure: False
iterations: 20000
interval: 100
