elements:
  - ["Cu", "Au", "Ag", "Mg", "Al", "Na", "Ca", "Fe", "Co", "W", "Cr"]
  # - ["O"]
  #- ["Cl"]

potentials:
  Cu: "openKIM:Sim_ASAP_EMT_Rasmussen_AgAuCu__SM_847706399649_000"
  Au: "openKIM:Sim_ASAP_EMT_Rasmussen_AgAuCu__SM_847706399649_000"
  Ag: "openKIM:Sim_ASAP_EMT_Rasmussen_AgAuCu__SM_847706399649_000"
  Mg: "openKIM:EAM_Dynamo_SunMendelevBecker_2006_Mg__MO_848345414202_005"
  Al: "openKIM:EAM_Dynamo_ZhouJohnsonWadley_2004NISTretabulation_Al__MO_060567868558_000"
  Na: "openKIM:EAM_Dynamo_NicholAckland_2016_Na__MO_048172193005_000"
  Ca: "openKIM:Morse_Shifted_GirifalcoWeizer_1959HighCutoff_Ca__MO_159753408472_004"
  Fe: "openKIM:EAM_Dynamo_AcklandBaconCalder_1997_Fe__MO_142799717516_005"
  Co: "openKIM:EAM_Dynamo_PunMishin_2012_Co__MO_885079680379_005"
  W: "openKIM:EAM_Dynamo_Ackland_2003_W__MO_141627196590_005"
  Cr: "openKIM:EAM_Dynamo_DeluigiPasianotValencia_2021_FeNiCrCoCu__MO_657255834688_000"
  default: "LJ"

cells:
  Na: "BCC" 
  Fe: "BCC"
  Default: "FCC"

