---
#-----------Simulation------------#
atomic_number: 18
epsilon: 0.010323 # eV
sigma: 3.40 # Å
cutoff: 6.625 # Å
# Insert None for the unused lattice constants (e.g. [3.569,None,None,None,None,None] for SC/FCC/BCC lattice) 
latticeconstants : [] #[a, b, c, alpha, beta, gamma], leave empty to use ase default
#bravaislattice currently only supports "SC", "FCC", "BCC" 
bravaislattice : "FCC" #(conventional unit cell)
directions : [[1,0,0], [0,1,0], [0,0,1]] #(use Miller-Bravais for hex-structure), hex currently not supported
#Customizable primitive unit cell, leave bravaislattice empty if cell is used.
cell: [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]] #(primitive unit cell vectors)
positions : [[0,0,0]] #Set position of each atom in the molecule
symbol : "Ar"
pbc : True #periodic boundary conditions
size : [10,10,10]
# Select between NVE (Velocity Verlet) for constant energy ensemble
# and NVT for constant temperature (Langevin) ensemble.
ensemble: "NVT"
NVT_friction: 0.02
temperature_K : 200
# Leave potential empty if running ASE, will resort to using EMT as potential.
potential: "LJ"
# simulation time step [fs]
dt: 5
iterations: 2000
output:
  - temperature
  - volume
interval: 20
openKIMid: "Sim_ASAP_EMT_Rasmussen_AgAuCu__SM_847706399649_000"


#-----------Analyse------------#
run_density: True
density_time: 1 #If wanted to specify what timestep the density is to be calculated. Empty = first timestep

run_MSD: True
MSD_time: #If wanted to specify what timestep the mean square displacement is to be calculated. Empty = first timestep

run_self_diffusion_coefficient: True
self_diffusion_coefficient_time: #If wanted to specify what timestep the self diffusion coefficient is to be calculated. Empty = first timestep

run_pressure: True


#-----------Visualize------------#
visualize:
  - temperature
run_density_plot: False
run_MSD_plot: False
